# Generated by Django 4.2.3 on 2023-07-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_banner_role_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillPercentage', models.PositiveSmallIntegerField(default=90)),
                ('stopColor1', models.CharField(max_length=20)),
                ('stopColor2', models.CharField(max_length=20)),
                ('skillName', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
