# Generated by Django 4.2.3 on 2023-07-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='stopColor1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='stopColor2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
