# Generated by Django 4.2.3 on 2023-07-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_skill_stopcolor1_alter_skill_stopcolor2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('imgUrl', models.CharField(max_length=200, unique=True)),
                ('tabIndex', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
