# Generated by Django 4.2.3 on 2023-07-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imgUrl',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
