# Generated by Django 4.2.3 on 2023-07-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_project_imgurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=20)),
                ('phoneNo', models.CharField(max_length=20, unique=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
