# Generated by Django 4.2.3 on 2023-07-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
